name: net
description: networking library
version: 0.1.1
homepage: https://github.com/hb1love/net

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  dartz: ^0.10.1
  equatable: ^2.0.3
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.21.1
  build_runner: ^2.0.0
  freezed: ^2.0.4
  json_serializable: ^6.3.1
  mockito: ^5.2.0

flutter:

